version: '3.8'

services:
  postgres:
    container_name: postgres_db_restful
    image: postgres:14-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_restful
    ports:
      - "5432:5432"
    volumes:
      - data_postgres_db_restful:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
      retries: 10
volumes:
  data_postgres_db_restful:
    external: false